### ISSUE TITLE
Make YML selectors available in DAG view

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-docs#119]
Re-opening the piece of #116 not resolved by #118

* Add version-controlled YML selectors, accessible via --selector flag, to DAG view

Here's what I'm thinking: add a new "Selectors" bottom-row component that auto-populates with the list of available YML selectors, similar to what we do today with tags and packages. If there are no YML selectors defined in the project, it would be missing.

**Comment by drewbanin** [comment]
@jtcohen6 i _love_ the idea of pre-populating the list of selectors. I also wonder... do you think there's a world where these selectors work more like "lenses" that sit on top of the entire Docs experience? Would be pretty neat to produce different sets of documentation geared towards different consumers. This might:
 - show/hide different objects in the file/database tree
 - default to the file/database tree view in the left-hand nav
 - render ERDs instead of DAGs (when we support ERDs) :D 

I don't want to do anything about any of this today, but this feels like one of those "a-ha" moments for me. I bet we're missing some key configurations in Core that will help us link up node selectors to "lenses".

Either way... let's address this in the docs site for 0.18.0 if we can :)

**Comment by drewbanin** [comment]
FYI @jtcohen6 it does not appear to me that yaml-based selectors are included in the manifest... which is going to make the implementation of this feature..... challenging

**Comment by jtcohen6** [comment]
Selectors <> lenses: _really_ cool idea. This plus "exposure"-driven "landing pages" could open up a lot of potential for curation.

Welp... the exclusion of named selectors from the manifest is definitely an oversight. We're adding _so_ much new node selection functionality in 0.18.0 as it is, so I think it's ok to push this back to v0.19.0 and make sure we do it right. What do you think makes most sense in terms of storing in manifest:
- the JSON representation of the YAML selector definition (you'd need to write more JS, hopefully just one layer on top of existing functional pieces)
- the full list of nodes included by the selector (easy to consume, but big files with lots of potential for duplication)
- some intermediate/abstracted (?) representation (?) of the list of selection rules (?)

**Comment by drewbanin** [comment]
Ok, I'm supportive of holding onto this change for the next release. I think that:
 - A json representation (not the raw YAML) would be ideal
 - We probably do not want an entire list of nodes that would be matched by each selector, but would instead benefit from the "expanded" set of node selector description. It would be ideal if the node shorthand (eg `models/my_dir/everything.*+`) was expanded out into its full json object representation. This will make it easiest for the docs site (or other artifact consumers) to operate on IMO.

**Comment by kwigley** [comment]
@jtcohen6 How should the the docs site handle the `state` selection method? I don't think it really makes sense for a docs site user, but I think we would need the list of matched nodes in order to do something useful.

**Comment by jtcohen6** [comment]
Given that dbt-docs are static today, and powered by only one set of artifacts, we just can't use `state` there. Can we exclude (or make un-selectable) any `selectors` that include `state`?
