### ISSUE TITLE
Ability to distinguish node colors by tags and packages (including resources)

### ISSUE THREAD

**Issue by stephen8chang** [dbt-labs/dbt-docs#124]
As of now, the coloring schema for the nodes in the table graph is limited to the respective resource of that node. To get an overarching visual view of the differences in tags, packages, and resources in the table graph, there should be a way to display a coloring schema of nodes in the table graph unique to the tags, packages, or resources of the nodes.

**Comment by comaraDOTcom** [comment]
Also wanted to say this feature is something I also think would be awesome. My use case is more related to `tests` specifically`data tests` not schema tests.

A little bit've context on how this crops up in testing for me:  I've a workflow with lots of custom data tests to check certain quantities are conserved etc through each step. All the tests appear as blue nodes (like models - this makes sense since they are creat table statements in the compiled sql). It would be really useful if these tests appeared in the DAG as a different colour (or the ability to customise this).
