### ISSUE TITLE
Export dbt docs to data catalogs?

### ISSUE THREAD

**Issue by zevektor** [dbt-labs/dbt-docs#177]
### Describe the feature
Currently, the dbt doc generates a static website listing all the models included in the project, their lineage, etc.
Many companies, however, already have a data catalog in place (e.g. Amundsen, Metacat, Atlas, etc.). 
Usually these data catalog solutions expose REST APIs to allow to insert/update metadata programmatically.

It would be great if the dbt docs command could generate all the JSON payloads necessary to insert/update documentation related to databases/tables/columns into such data catalogs.

### Describe alternatives you've considered
N/A

### Additional context
N/A

### Who will this benefit?
All the users whose company already has a data catalog in place and don't want a subset of data assets to be documented somewhere else.

### Are you interested in contributing this feature?
I might code something related to the data catalog I am interested to integrate, but I think this feature might work well if someone more capable than me designs an abstraction layer that can be extended to integrate multiple catalog systems following a defined pattern.

**Comment by jtcohen6** [comment]
Hey @zevektor! All the information in the dbt-docs site is pulled from the `manifest.json` and `catalog.json` artifacts produced by the `dbt docs generate` command. As of the most recent version of dbt (v0.19.0), those artifacts are documented and versioned:

https://docs.getdbt.com/reference/artifacts/dbt-artifacts
https://schemas.getdbt.com/

dbt artifacts are the established contract for parsing, ingesting, querying, or otherwise using rich dbt metadata. If you're interested in integrating that information into other data catalogs or metadata solutions, these JSON files are the right place to start.

> Usually these data catalog solutions expose REST APIs to allow to insert/update metadata programmatically.

While not in scope for this repo, this is possibly of interest: dbt Cloud has preview support for a metadata (graph) API to expose the same information, by means of ingesting and flattening the same JSON artifacts from historical runs. If you're interested, you can check out the [dbt Cloud changelog](https://docs.getdbt.com/docs/dbt-cloud/cloud-changelog/) and join the #beta-metadata channel in [dbt Slack](https://community.getdbt.com/).

**Comment by kevnoo** [comment]
@zevektor - we have been experimenting with  persist_docs = True so that we can place a rest api on top of our Snowflake information schema. I don't think its exactly what you are looking for but thought I'd share anyway.
