### ISSUE TITLE
databricks sample SQL has a dot before the schema name

### ISSUE THREAD

**Issue by martinburch** [dbt-labs/dbt-docs#264]
### Describe the bug
When using the **[dbt-databricks](https://github.com/databricks/dbt-databricks)** adapter, the Sample SQL generated by dbt-docs (core version v1.0.1) contains a dot before the relation name, **[Yikun Song reports on dbt Slack](https://getdbt.slack.com/archives/CBSQTAPLG/p1650456653012479)**. This makes the query invalid.

```sql
SELECT
...
FROM .clean__schema_name.table_name
```

### Expected behavior
The relation should be referenced without the leading dot, as e.g. `FROM clean__schema_name.table_name`

### Why is this happening?
As Benoit says
> There is a dot because normally dbt is providing the format database.schema.table but I think that databricks/spark do not use a concept of database

The [`generateSourceSQL` function in code_service.js](https://github.com/dbt-labs/dbt-docs/blob/5f791fe466906df556855b0f2ac2fd9ff29019fc/src/app/services/code_service.js#L52) has the faulty logic:
`var rel = [model.database, model.schema, model.identifier || model.alias || model.name].join(".");`

### Suggested fix

As a fix, I’d suggest using the relation-building logic seen in `table_details.js`: https://github.com/dbt-labs/dbt-docs/blob/5f791fe466906df556855b0f2ac2fd9ff29019fc/src/app/components/table_details/table_details.js#L81-L95

**Comment by emmyoop** [comment]
@martinburch this is a stellar write up!  Thank you for taking the time to figure out where the problem was coming from and even coming up with a solution!  

I saw in the slack thread you don't have the time to contribute this PR.  If you change your mind or if anyone else from the community is up for it, we would welcome a PR to fix this.  You seem to have covered what needs to happen to fix this.
