### ISSUE TITLE
[CT-1187] meta isn't searchable in dbt docs

### ISSUE THREAD

**Issue by eunie1o6** [dbt-labs/dbt-docs#305]
### Describe the bug
Meta isn't searchable in dbt docs using the --select criteria. As an example, the following would run fine:

```
dbt run --select config.meta.frequency:daily

dbt ls --select config.meta.frequency:daily
```
However, passing `config.meta.frequency:daily` next to --select in the lineage graph does not return anything.

The meta values correctly show up in the model docs, and in manifest.json.

Searching by other configs, such as `config.materialized:incremental` works as expected in docs, so this issue appears to be specific to meta for now.

### Steps To Reproduce
1. Configure a model to have a meta value like so:
```
{{ config(meta = {"frequency": "daily"}) }}
```
2. Generage dbt docs.
3. Serve dbt docs.
4. Open lineage graph, and enter `config.meta.frequency:daily` next to --select, and update chart. Nothing should appear if reproduced.

### Expected behavior
I would expect that the models that are configured with that meta key value pair to display in the graph, along with its dependencies if graph operators are used.

### Screenshots and log output

**The output of `dbt --version`:**
```
Core:
  - installed: 1.2.1
  - latest:    1.2.1 - Up to date!

Plugins:
  - bigquery: 1.2.0 - Up to date!
```

### Additional context
The reason for using meta in this way over tags is to allow the value to get overwritten if it gets specified as a more specific level of the hierarchy. The additive nature of tags results in confusing combinations of frequencies if applied at multiple levels.

**Comment by jtcohen6** [comment]
Ultimately, this is because of how we've implemented node selection logic: in Python in `dbt-core`, and then _again_ in JavaScript in `dbt-docs`. Gross. Inevitably, there are going to be some discrepancies.

In this specific case, it has to do with digging through dictionary configs to match on nested key-value pairs. The [core Python logic](https://github.com/dbt-labs/dbt-core/blob/987764858b81b95d8b93dcce67a4a9aace532ba3/core/dbt/graph/selector_methods.py#L336-L371) does it, but the JS doesn't:

https://github.com/dbt-labs/dbt-docs/blob/4d8cc4dcc734ec6105225ec08e430621b5a4fbc8/src/app/services/selector_matcher.js#L184-L195

**Short-term fix:** Implement the same logic in JS.

**Longer-term fix:** Find a way to power node selection in `dbt-docs` using _the exact same library code_ that powers node selection in `dbt-core`.

This isn't something we're likely to prioritize. I'd rather spend our energies on creating better internal APIs within the `dbt-core` library, and figuring out a future documentation site that can leverage a real "dbt backend."
