### ISSUE TITLE
[CT-1497] node_color set to RebeccaPurple makes the lineage graph render weird

### ISSUE THREAD

**Issue by rsanjabi** [dbt-labs/dbt-docs#344]
### Describe the bug
Setting `node_color` attribute to _RebeccaPurple_ will make the lineage graph render odd and behave weirdly. 

### Steps To Reproduce

In dbt core 1.3 within `dbt_project.yml` added _RebeccaPurple_ as a node_color.
```
  my_project_name:
    marts:
      core:
        +docs:
          node_color: "RebeccaPurple"
```
From CLI do a`dbt docs generate` (no errors) then `dbt docs serve` then navigate to lineage graph.

### Expected behavior
Within the documentation I'm expecting to see a typical lineage graph except all core models will be in a pleasing shade of purple.

### Screenshots and log output
 Rendered lineage graph:
![image](https://user-images.githubusercontent.com/47192430/201400407-0469332b-d970-414e-84b8-0a185a9f2cb1.png)
Interacting with the select filters when place all the nodes on top of each other.
![image](https://user-images.githubusercontent.com/47192430/201400800-cbef092e-ec51-46fb-b6d1-4038054e0146.png)

### Additional context

- All lowercase and mixed case and that didn't matter.
- Tried on 2 different projects
- Some other color names that I tried that worked _HotPink_, _BurlyWood_, _DeepSkyBlue_, _gray_, _powderblue_
- _RebeccaPurple_ was added to [CSS4](https://en.wikipedia.org/wiki/Web_colors#CSS_Color_4) so perhaps it's an outlier and should not be included in list of acceptable colors except it has a very poignant story behind it and purple people want all the purples.

**Comment by jtcohen6** [comment]
@rsanjabi Thanks for opening! The [wikipedia page you linked](https://en.wikipedia.org/wiki/Web_colors) is a fun one; I could see someone losing an afternoon to the history of "display-safe" color development.

This is the console error I see while trying to load the docs:
```
(index):79 The style property `background-color: rebeccapurple` is invalid
```
I'm not sure where exactly that error is coming from—but I have to guess it's our use of an older library, given that a lot of `dbt-docs` code is getting on in age. (It's all newer than 2014, though, which is when CSS4 / `RebeccaPurple` was introduced.)

As you mention, we do validate colors before trying to set them as properties:

https://github.com/dbt-labs/dbt-docs/blob/a00489951e970c9a74e235c12c231ab51ea905bc/src/app/services/validate_node_color.js#L147-L157

https://github.com/dbt-labs/dbt-docs/blob/a00489951e970c9a74e235c12c231ab51ea905bc/src/app/services/validate_node_color.js#L116

We have the same code in `dbt-core`, too, to catch invalid color names at parse time — [here's the `validate_color` function](https://github.com/dbt-labs/dbt-core/blob/32415e365961cb453e2a4dd5f5002461848f1202/core/dbt/contracts/graph/utils.py#L150-L153), [here's where `rebeccapurple` appears in the list](https://github.com/dbt-labs/dbt-core/blob/32415e365961cb453e2a4dd5f5002461848f1202/core/dbt/contracts/graph/utils.py#L119).

Two thoughts:
- It seems like a good way to guard against this would be to proactively convert color names into hex codes, and use the default color if no valid hex code is returned. If we have static lists of valid color names, we might as well include the static list of their hex codes as well.
- Then again, should we be defining these color lists ourselves, or using a package for it? (In Python: https://webcolors.readthedocs.io/en/1.12/; in JS, one of the approaches mentioned in https://stackoverflow.com/questions/1573053/javascript-function-to-convert-color-names-to-hex-codes.) It sounds like new colors are added quite infrequently. Still, I'd hate to need PRs in two repos to update the same static list in both places.

Going to mark this one as `help_wanted`, for anyone who's interested in pursuing the work to turn `isValidColor` into a function that always returns a hex (rather than a boolean go / no-go).

**Comment by jtcohen6** [comment]
@rsanjabi Thanks for opening! The [wikipedia page you linked](https://en.wikipedia.org/wiki/Web_colors) is a fun one; I could see someone losing an afternoon to the history of "display-safe" color development.

This is the console error I see while trying to load the docs:
```
(index):79 The style property `background-color: rebeccapurple` is invalid
```
I'm not sure where exactly that error is coming from—but I have to guess it's our use of an older library, given that a lot of `dbt-docs` code is getting on in age. (It's all newer than 2014, though, which is when CSS4 / `RebeccaPurple` was introduced.)

As you mention, we do validate colors before trying to set them as properties:

https://github.com/dbt-labs/dbt-docs/blob/a00489951e970c9a74e235c12c231ab51ea905bc/src/app/services/validate_node_color.js#L147-L157

https://github.com/dbt-labs/dbt-docs/blob/a00489951e970c9a74e235c12c231ab51ea905bc/src/app/services/validate_node_color.js#L116

We have the same code in `dbt-core`, too, to catch invalid color names at parse time — [here's the `validate_color` function](https://github.com/dbt-labs/dbt-core/blob/32415e365961cb453e2a4dd5f5002461848f1202/core/dbt/contracts/graph/utils.py#L150-L153), [here's where `rebeccapurple` appears in the list](https://github.com/dbt-labs/dbt-core/blob/32415e365961cb453e2a4dd5f5002461848f1202/core/dbt/contracts/graph/utils.py#L119).

Two thoughts:
- It seems like a good way to guard against this would be to proactively convert color names into hex codes, and use the default color if no valid hex code is returned. If we have static lists of valid color names, we might as well include the static list of their hex codes as well.
- Then again, should we be defining these color lists ourselves, or using a package for it? (In Python: https://webcolors.readthedocs.io/en/1.12/; in JS, one of the approaches mentioned in https://stackoverflow.com/questions/1573053/javascript-function-to-convert-color-names-to-hex-codes.) It sounds like new colors are added quite infrequently. Still, I'd hate to need PRs in two repos to update the same static list in both places.

Going to mark this one as `help_wanted`, for anyone who's interested in pursuing the work to turn `isValidColor` into a function that always returns a hex (rather than a boolean go / no-go).

**Comment by stu-k** [comment]
@jtcohen6 I think the safer solution here is to only include CSS3 colors into the list of allowed colors and remove `rebeccapurple`. I don't believe we should be converting valid CSS color names into hex values ourselves, that's the job of the browser. Should users want a particular color, providing a hex value should suffice.

**Comment by jtcohen6** [comment]
@stu-k Ok! Let's open a new issue then to just remove `rebeccapurple`, here and in `dbt-core`? Anyone who wants to use it can supply it as `#663399`.

**Comment by stu-k** [comment]
@jtcohen6 This makes sense to me!
