### ISSUE TITLE
[CT-1807] Metrics should show yaml instead of compiled SQL in documentations

### ISSUE THREAD

**Issue by kalanyuz** [dbt-labs/dbt-docs#357]
### Describe the feature
Since we write metric definitions in yaml to create semantic layer, the code section of metrics show the yaml definition and not compile SQL code.

### Describe alternatives you've considered
Add another tab for YAML instead of replacing the code section entirely.

### Are you interested in contributing this feature?
Yes. I would need a lead on where should I look to add this feature.

**Comment by callum-mcdata** [comment]
Hi @kalanyuz! I think we're directionally aligned on the fact that we want to expose more metric information inside the documentation but diverge slightly on how we'd like to do so. Instead of showing the `yaml` in the code section, we'd rather introduce all of the elements as `details`. 

Given the dynamic nature of metrics, we may also want to remove the code section, as the sql associated with each metric is entirely dependent on how it is queried.

**Comment by kalanyuz** [comment]
@callum-mcdata I'm happy to help out with this if you could point me to where to look.
