### ISSUE TITLE
[CT-1910] Add eslint and prettier [tech debt]

### ISSUE THREAD

**Issue by mattyb** [dbt-labs/dbt-docs#364]
### Describe the feature
[eslint](https://www.npmjs.com/package/eslint) and prettier are the js equivalent of flake8 and black used in [dbt-core](https://github.com/dbt-labs/dbt-core). When I was working on #363 I noticed a lot of variation in whitespace usage that I was tempted to fix but wanted to avoid adding too much noise to the PR. Eslint and prettier are common tools used in js development to maintain readability and reduce unnecessary changes due to varying code styles.

### Implementation details
- eslint and prettier should be [configured to work together](https://github.com/prettier/eslint-plugin-prettier#recommended-configuration)
- eslint should run in a github workflow
- put the first commit of changes from prettier into a [`.git-blame-ignore-revs` file](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view), so the whole blame isn't taken over with whitespace changes 

### Describe alternatives you've considered
Skipping prettier is simpler, and we could leave formatting checks to eslint, but this seems out of step with the decisions made in dbt-core

### Additional context
n/a

### Who will this benefit?
Contributors and reviewers.

### Are you interested in contributing this feature?
Sure

**Comment by dbeatty10** [comment]
All this makes sense and thanks for laying out those implementation details @mattyb !

We'd review this if you're willing to contribute this.

We squash and merge all of our pull requests. Would that mean that the first commit of changes from prettier should be in a stand-alone PR so that a follow-up PR can add that commit into [.git-blame-ignore-revs file](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view)?
