### ISSUE TITLE
[CT-2885] Column type should be more detailed.

### ISSUE THREAD

**Issue by thomasaarholt** [dbt-labs/dbt-docs#439]
### Describe the feature
The dtype on the column description should include more detailed information. For instance, it would be nice if it was clear that Number was a `Decimal(38, 0)` type in this case, to make it easier to be certain that a number type can't have decimals (or might not have enough!).

<img width="755" alt="image" src="https://github.com/dbt-labs/dbt-docs/assets/2721423/04eab76c-b573-4aba-bcff-90295c0f74fd">

### Additional context
I use Snowflake, where Number types are always Decimal types.

### Who will this benefit?
Helps analysts or engineers diagnose problems more quickly than opening the database.

### Are you interested in contributing this feature?
I might be able to, but am not used to working with the dbt codebase.

**Comment by dbeatty10** [comment]
Thanks for raising this suggestion @thomasaarholt 🧠 

For purposes of backwards compatibility with [catalog.json v1](https://schemas.getdbt.com/dbt/catalog/v1.json) schema, we'd probably keep `type` as having no additional parameters.

But in the future, I could see us choosing to implement one or both of the following within [`catalog.json`](https://docs.getdbt.com/reference/artifacts/catalog-json):
1. parameterized version of the data type
    - like `varchar(256)`, `decimal(38, 0)`, or `timestamp(6)`
2. fields from the [`information_schema.columns`](https://www.postgresql.org/docs/current/infoschema-columns.html) view (as defined in [ISO/IEC 9075-11](https://en.wikipedia.org/wiki/ISO/IEC_9075))
    - in particular a minimal viable subset like `character_maximum_length`, `numeric_precision`, `numeric_scale`, and `datetime_precision`
    - and possibly the rest of the fields or some other subset
    
Since we're not planning on adding these to `catalog.json` at this time, I'm going to close this issue as [`wontfix`](https://docs.getdbt.com/community/resources/oss-expectations#issue-labels). We may revisit this in the future 📆
