### ISSUE TITLE
"Edit this definition" link

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-docs#92]
### Describe the feature
Viewers of a given resource page in the auto-generated documentation site should be able to click a link that directs them to the appropriate configuration file in the dbt project git repository, such that they could edit descriptions for that resource.

### Challenges

* Each manifest node would need to store the path to the YML file which configures it. As I understand it, the manifest includes configuration file paths for sources but not for models.
* The dbt project / docs needs to somehow know the URL of its repository. This makes more sense in dbt Cloud than it does in dbt core.

### Alternatives
* A more involved implementation would direct users to the specific line with the description of a given model/column. I think directing users to the right YML file is good enough for the V1.
* This is much easier to build vs. an interface that would allow viewers to live-edit docs!

### Who will this benefit?
Organizations with more active/engaged docs viewers

**Comment by clrcrl** [comment]
A few other things I was thinking

**Should we do this at the model level only, or also at the column level?**
Related to:
> A more involved implementation would direct users to the specific line with the description of a given model/column.

I _was_ thinking that we should do this at the column-level. It would be cool to have a ✏️ icon on each column description so that people could jump straight to the right line, especially when schema.yml files can get really long!

**Should we try to resolve it do a markdown file if a docs block is used?**
No. I think it would potentially be impossible —  you can mix and match plain text and docs blocks, and I don't think the Jinja parser has a way to know where the ultimate piece of context came from.

**Where else does this approach exist?**
Inspiration for this is the docusaurus "edit this page" button (check it out on each page of docs.getdbt.com, and see the [docs](https://docusaurus.io/docs/en/site-config#editurl-string) to configure the setting here).

**Comment by tayloramurphy** [comment]
Would love to see this implemented! Even just the simple link to the model definition would be helpful. Including tests and sources would be 🔥 as well.
